### SURF (Speeded-Up Robust Features)
* OpenCV의 surf 함수를 이용하기 위해서는 opencv-contrib-python이 설치되어야 함

In [4]:
import cv2
import numpy as np

img = cv2.imread('./images/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# SURF 추출기 생성 (임계값:1000, 피라미드:3, 서술자확장:True, 방향적용:True)
surf = cv2.SURF_create(1000, 3, True, True)  # opencv-contrib 버전 설치 필요

# 키 포인트 검출과 서술자 계산
keypoints, descriptor = surf.detectAndCompute(gray, None)
print('keypoint:',len(keypoints), 'descriptor:', descriptor.shape)
print(descriptor)

# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# 결과 출력
cv2.imshow('SURF', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

keypoint: 5002 descriptor: (5002, 128)
[[  4.   0.   0. ...   5.   0.   0.]
 [ 11.   5.   0. ...   5.  18. 121.]
 [  4.   2.   3. ...   0.   0.   0.]
 ...
 [  0.   0.  70. ...   0.   0.   0.]
 [  0.   0.   0. ...   1.  27. 125.]
 [  0.   4.  24. ...   0.   0.   0.]]
