### BFMatcher 디스크립터 매칭기

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img1 = cv2.imread('./images/pica.jpg')
img2 = cv2.imread('./images/figures.jpg')

gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# SIFT 서술자 추출기 생성 ---①
detector = cv2.xfeatures2d.SIFT_create()
# 각 영상에 대해 키 포인트와 서술자 추출 ---②
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)

# BFMatcher 생성, L1 거리, 상호 체크 ---③
matcher = cv2.BFMatcher(cv2.NORM_L1, crossCheck=True)
# 매칭 계산 ---④
matches = matcher.match(desc1, desc2)
# 매칭 결과 그리기 ---⑤
res = cv2.drawMatches(img1, kp1, img2, kp2, matches, None, \
                      flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)
# 결과 출력 

plt.figure(figsize = (10,6))
imgs = {'BFMatcher + SIFT':res}
for i, (k, v) in enumerate(imgs.items()):
    plt.subplot(1,1,i+1)
    plt.title(k)
    plt.imshow(v[:,:,(2,1,0)])
    plt.xticks([]),plt.yticks([])

plt.show()

[[[175 165 165]
  [175 165 165]
  [175 165 165]
  ...
  [169 156 154]
  [172 157 155]
  [172 157 155]]

 [[177 167 167]
  [177 167 167]
  [177 167 167]
  ...
  [172 159 157]
  [173 158 156]
  [173 158 156]]

 [[177 167 167]
  [177 167 167]
  [177 167 167]
  ...
  [175 160 158]
  [175 160 158]
  [175 160 158]]

 ...

 [[167 159 159]
  [166 158 158]
  [167 159 159]
  ...
  [162 160 160]
  [162 160 160]
  [162 160 160]]

 [[166 158 158]
  [167 159 159]
  [167 159 159]
  ...
  [162 160 160]
  [162 160 160]
  [162 160 160]]

 [[166 158 158]
  [168 160 160]
  [167 159 159]
  ...
  [162 160 160]
  [162 160 160]
  [162 160 160]]]


AttributeError: module 'cv2' has no attribute 'xfeatures2d'